# Generated by Django 5.2.9 on 2026-01-11 23:26

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirtySecrets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('login_name', models.TextField(default=None, max_length=300)),
                ('login_created_date', models.TextField(default=None, max_length=300)),
                ('login_work_group', models.TextField(default=None, max_length=300)),
                ('login_comment', models.TextField(default=None, max_length=300)),
                ('login_encrypted_password', models.TextField(default=None, max_length=300)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('login_name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('storage_name', models.TextField(default=None, max_length=300)),
                ('storage_comment', models.TextField(default=None, max_length=300)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('storage_name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('inventory_name', models.TextField(default=None, max_length=300)),
                ('inventory_type', models.TextField(default=None, max_length=300)),
                ('inventory_number', models.TextField(default=None, max_length=300)),
                ('inventory_comment', models.TextField(default=None, max_length=300)),
                ('inventory_status', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('inventory_device_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.device')),
                ('inventory_vendor', models.ForeignKey(blank=True, max_length=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.manufacturer')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('inventory_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_reference', to='ratnet.storage')),
            ],
            options={
                'ordering': ('inventory_name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
