# Generated by Django 5.2.9 on 2026-01-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_status',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
