# Generated by Django 5.2.9 on 2026-01-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratnet', '0002_alter_inventory_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_comment',
            field=models.TextField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_number',
            field=models.TextField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_status',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.TextField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
