# Generated by Django 5.2.9 on 2026-01-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratnet', '0003_alter_inventory_inventory_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_device_usage',
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_nums',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
