# Generated by Django 5.2.9 on 2026-01-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratnet', '0004_remove_inventory_inventory_device_usage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='inventory_nums',
            new_name='inventory_amount',
        ),
    ]
